import type { NextPage } from "next";
import Head from "next/head";
import { Box, Container } from "@mui/material";
import Hero from "../src/components/Hero";
import AppHeader from "../src/components/AppHeader";
import WhatYouGetSection from "../src/components/WhatYouGetSection";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppHeader></AppHeader>
      <Hero />
      <Container sx={{ my: 4 }}>
        <WhatYouGetSection />
      </Container>
    </Box>
  );
};

export default Home;
